checkpoint_dir: work_dir/train_2d_3d_fusion_debug

test_mode: False

lr: 0.0001
optimizer: Adam
lr_decay_step: 12
lr_decay_rate: 0.2
wd: 0

learning_rate: 1e-4
decay_rate: 1.0
epoch_num: 5000
adam_beta1_value: 0.9

num_render_sequences: 3

dataset:
  data_root: ./data/id00002
  batch_size: 2
  number_workers: 4


d_model: 128

Face2D3DXFormer:
  d_model: 128
  nhead: 4
  n_layer: 2
  d_feed_forward: 256

mm_fusion_decoder:
  d_model: 128
  n_head: 4
  n_layer: 2
  d_feed_forward: 1024

face_3dmm_former:
  d_input_3d_params: 64
  d_model: 128
  n_head: 4
  n_layer: 1
  d_feed_forward: 256

log:
  checkpoint_dir: training_exp