checkpoint_dir: work_dir/train_2d_with_val_best_ckpt

learning_rate: 1e-4
decay_rate: 1.0
epoch_num: 5000
adam_beta1_value: 0.9

num_render_sequences: 3

dataset:
  data_root: /home/haimingzhang/Research/Face/FACIAL/video_preprocessed/id00002
  batch_size: 4
  number_workers: 4

face_gen_former_decoder:
  d_model: 128
  n_head: 4
  n_layer: 1
  d_feed_forward: 1024

log:
  checkpoint_dir: training_exp