checkpoint_dir: training_viz2   
expression_basis_fname: ./training_data/init_expression_basis.npy
template_fname: ./template/FLAME_sample.ply
deepspeech_graph_fname: ./ds_graph/output_graph.pb
verts_mmaps_path: ./training_data/data_verts.npy
raw_audio_path: ./training_data/raw_audio_fixed.pkl
templates_path: ./training_data/templates.pkl
data2array_verts_path: ./training_data/subj_seq_to_idx.pkl
processed_audio_path: ./training_data/processed_audio_deepspeech.pkl

audio_feature_type: deepspeech
num_audio_features: 29
audio_window_size: 16
audio_window_stride: 1
condition_speech_features: True
speech_encoder_size_factor: 1.0

num_vertices: 5023
expression_dim: 50
init_expression: True
num_consecutive_frames: 2
absolute_reconstruction_loss: False
velocity_weight: 10.0
acceleration_weight: 0.0
verts_regularizer_weight: 0.0

subject_for_training: FaceTalk_170728_03272_TA
sequence_for_training: sentence01
subject_for_validation: FaceTalk_170811_03275_TA FaceTalk_170908_03277_TA
sequence_for_validation: sentence21 sentence22 sentence23 sentence24 sentence25 sentence26 sentence27 sentence28 sentence29 sentence30 sentence31 sentence32 sentence33 sentence34 sentence35 sentence36 sentence37 sentence38 sentence39 sentence40
subject_for_testing: FaceTalk_170809_00138_TA FaceTalk_170731_00024_TA 
sequence_for_testing: sentence21 sentence22 sentence23 sentence24 sentence25 sentence26 sentence27 sentence28 sentence29 sentence30 sentence31 sentence32 sentence33 sentence34 sentence35 sentence36 sentence37 sentence38 sentence39 sentence40

batch_size: 1
learning_rate: 1e-4
decay_rate: 1.0
epoch_num: 200
adam_beta1_value: 0.9

num_render_sequences: 3

dataset:
  batch_size: 1
  subject_for_training: FaceTalk_170728_03272_TA
  sequence_for_training: sentence01
  subject_for_validation: FaceTalk_170811_03275_TA FaceTalk_170908_03277_TA
  sequence_for_validation: sentence21 sentence22 sentence23 sentence24 sentence25 sentence26 sentence27 sentence28 sentence29 sentence30 sentence31 sentence32 sentence33 sentence34 sentence35 sentence36 sentence37 sentence38 sentence39 sentence40
  subject_for_testing: FaceTalk_170809_00138_TA FaceTalk_170731_00024_TA 
  sequence_for_testing: sentence21 sentence22 sentence23 sentence24 sentence25 sentence26 sentence27 sentence28 sentence29 sentence30 sentence31 sentence32 sentence33 sentence34 sentence35 sentence36 sentence37 sentence38 sentence39 sentence40

  expression_basis_fname: ./training_data/init_expression_basis.npy
  template_fname: ./template/FLAME_sample.ply
  verts_mmaps_path: ./training_data/data_verts.npy
  raw_audio_path: ./training_data/raw_audio_fixed.pkl
  templates_path: ./training_data/templates.pkl
  data2array_verts_path: ./training_data/subj_seq_to_idx.pkl
  sequence_length: 60



final_channels: 15069
motion_embedding_dim: 128
style_embedding_dim: 128

faceformer_decoder:
  d_model: 128
  n_head: 4
  n_layer: 1
  d_feed_forward: 256

  d_motion_decoder: 15069 # 5023*3
  
