## Using the masked mouth
checkpoint_dir: work_dir2/train_2d_3d_fusion_HDTF
test_mode: False

model_name: Face2D3DFusion

pretrained_gan_checkpoint: null
checkpoint: null

## Trainer parameters
check_val_every_n_epoch: 2
max_epochs: 200

lr: 1e-4
optimizer: Adam
adam_beta1_value: 0.9
wd: 0

lr_decay_step: 10
lr_decay_rate: 0.2

load_mouth_mask: True

dataset:
  data_root: ./data/HDTF_preprocessed
  batch_size: 2
  fetch_length: 50
  number_workers: 4
  load_ref_image: False
  load_mouth_mask: ${load_mouth_mask}
  input_channel: 3

lambda_feat: 10.0

use_3d: True

PatchGANDiscriminator:
  ndf: 64            # num of discrim filters in first conv layer
  n_layers_D: 3      # number of layers in discriminator
  num_D: 2           # number of patch scales in each discriminator
  no_ganFeat: False  # do not match discriminator features
  lambda_feat: ${lambda_feat}

d_model: 128

Face2D3DXFormer:
  d_model: ${d_model}
  nhead: 4
  n_layer: 2
  d_feed_forward: 256

  use_3d: ${use_3d}
  use_3d_mask: False # whether to use 3D mask like SAT
  test_mode: ${test_mode}

  ImageTokenEncoder192:
    input_channel: ${dataset.input_channel}